# Generated by Django 5.0.2 on 2024-05-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='md_chapter',
            fields=[
                ('id_chapter', models.AutoField(primary_key=True, serialize=False)),
                ('chapter', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'db_table': 'md_chapter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MdDivision',
            fields=[
                ('id_division', models.AutoField(primary_key=True, serialize=False)),
                ('division', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'db_table': 'md_division',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MdMethodicalSolution',
            fields=[
                ('id_methodical_solution', models.AutoField(primary_key=True, serialize=False)),
                ('decision', models.CharField(max_length=150)),
                ('note', models.CharField(max_length=75)),
                ('marks_of_completion', models.CharField(max_length=20)),
                ('reason_for_nonfulfillment', models.CharField(max_length=75)),
                ('md_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Методическое решение',
                'verbose_name_plural': 'Методические решения',
                'db_table': 'md_methodical_solution',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MdPeriod',
            fields=[
                ('id_period', models.AutoField(primary_key=True, serialize=False)),
                ('period', models.CharField(max_length=21)),
            ],
            options={
                'verbose_name': 'Период',
                'verbose_name_plural': 'Периоды',
                'db_table': 'md_period',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MdResponsible',
            fields=[
                ('id_responsible', models.AutoField(primary_key=True, serialize=False)),
                ('responsible', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Ответстыенный',
                'verbose_name_plural': 'Ответстыенные',
                'db_table': 'md_responsible',
                'managed': False,
            },
        ),
    ]
